### ISSUE TITLE
skizze-cli - Missing parameters on command 'create dom' throw 'index out of range' exception

### ISSUE THREAD

**Issue by martinpinto** [skizzehq/skizze#104]
When leaving out the 4th and 5th parameter (e.g. create dom demo) skizze-cli crashes and throws an 'index out of range exception'.

Instead it should display an 'Invalid operation' message.

**Comment by martinpinto** [comment]
This seems to be fixed by now.

**Comment by martinpinto** [comment]
**Steps to Reproduce:**

1. Start skizze-cli (e.g. ./bin/skizze-cli)
2. type: "create dom users" (leave `<size>` and `<maxUniqueItems>` out) then enter

**Error:**
panic: runtime error: index out of range

```
> goroutine 1 [running]:
> skizze-cli/bridge.createDomain(0xc8201a6080, 0x3, 0x4, 0xc8201a60c0, 0x0, 0x0)
> 	/Users/martinpinto/go/src/github.com/seiflotfy/skizze/src/skizze-cli/bridge/domain.go:21 +0x8f6
> skizze-cli/bridge.sendDomainRequest(0xc8201a6080, 0x3, 0x4, 0x0, 0x0)
> 	/Users/martinpinto/go/src/github.com/seiflotfy/skizze/src/skizze-cli/bridge/domain.go:67 +0x476
> skizze-cli/bridge.evaluateQuery(0xc8201b6020, 0x11, 0x0, 0x0)
> 	/Users/martinpinto/go/src/github.com/seiflotfy/skizze/src/skizze-cli/bridge/loop.go:157 +0x5e9
> skizze-cli/bridge.Run.func2(0xc8200c8640)
> 	/Users/martinpinto/go/src/github.com/seiflotfy/skizze/src/skizze-cli/bridge/loop.go:229 +0x295
> github.com/codegangsta/cli.(*App).Run(0xc8200c8500, 0xc82000a280, 0x1, 0x1, 0x0, 0x0)
```
